// Array of first names.
export const companyNames: string[] = [
  "Cummins",
  "Williams",
  "VF",
  "Universal Health Services",
  "Fiserv",
  "PulteGroup",
  "NGL Energy Partners",
  "PNC Financial Services",
  "Coca-Cola",
  "Cheniere Energy",
  "Eastman Chemical",
  "JetBlue Airways",
  "Yum Brands",
  "Interpublic Group",
  "Northrop Grumman",
  "National Oilwell Varco",
  "Peabody Energy",
  "Westlake Chemical",
  "Reinsurance Group of America",
  "Anadarko Petroleum",
  "Penske Automotive Group",
  "PPG Industries",
  "Abbott Laboratories",
  "Hertz Global Holdings",
  "Eversource Energy",
];

export const firstNames: string[] = [
  "Aidan",
  "Sharon",
  "Leonidas",
  "Mikaela",
  "Chase",
  "Kathleen",
  "Zaid",
  "Paul",
  "Issac",
  "Ethen",
  "Vaughn",
  "Chasity",
  "Magdalena",
  "Coleman",
  "Sofia",
  "Cecelia",
  "Alannah",
  "Moses",
  "Irvin",
  "Ayana",
  "Eliana",
  "Veronica",
  "Tristian",
  "Hector",
  "Cherish",
  "Taniyah",
  "Camilla",
  "Nathalia",
  "Jaron",
  "Cecelia",
  "Bobby",
  "Marcel",
  "Miriam",
  "Emerson",
  "Juliet",
  "Isaias",
  "Makhi",
  "Charity",
  "Jake",
  "Nadia",
];

// Array of surnames.
export const lastNames: string[] = [
  "Vasquez",
  "Abbott",
  "Preston",
  "Ashley",
  "Yu",
  "Avila",
  "Douglas",
  "Strickland",
  "Yoder",
  "Todd",
  "Alexander",
  "Kim",
  "Garrett",
  "Boyle",
  "Combs",
  "Macdonald",
  "Johnson",
  "Cobb",
  "Choi",
  "Kelley",
  "Gaines",
  "Lam",
  "Pittman",
  "Jacobson",
  "Bruce",
  "Ballard",
  "Kramer",
  "Boyer",
  "Lee",
  "Jackson",
  "Lang",
  "Cordova",
  "Crane",
  "Hill",
  "Mcneil",
  "Donaldson",
  "Vance",
  "Pearson",
  "Guzman",
  "Rangel",
];

// Random list of job titles
export const titles: string[] = [
  "CEO",
  "President",
  "VP of Marketing",
  "VP of Engineering",
  "VP of HR",
  "VP of Sales",
  "Director of Engineering",
  "Director of Marketing",
  "Director of Sales",
  "Director of HR",
  "Senior Software Engineer",
  "Senior Sales Engineer",
  "Senior Support Analyst",
  "Senior Data Scientist",
];
