openapi: 3.0.1
info:
  title: 'Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  /api/company/add:
    post:
      tags:
        - Company
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
          text/json:
            schema:
              $ref: '#/components/schemas/Company'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Company'
      responses:
        '200':
          description: Success
  '/api/company/delete/{id}':
    delete:
      tags:
        - Company
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  '/api/company/{id}':
    get:
      tags:
        - Company
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: string
          nullable: true
        label:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
        webUrl:
          type: string
          nullable: true
      additionalProperties: false