# This workflow builds and deploys the front-end to Azure Static Web Apps

name: Build and Deploy Web

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: [ web/** ]
  pull_request:
    branches: [ main ]
    paths: [ web/** ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup node
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        working-directory: ./web
        run: yarn

      - name: Build for production using vite
        working-directory: ./web
        run: VITE_API_ENDPOINT=${{ secrets.VITE_API_ENDPOINT }} yarn run build --base=${{ secrets.GCP_BASE_URL }}

      # See docs: https://github.com/google-github-actions/upload-cloud-storage
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v0'
        with:
          path: './web/dist'
          destination: 'dn6-mongo-web' # Your bucket name here
